### ISSUE TITLE
异地登录京东会有短信验证问题

### ISSUE THREAD

**Issue by doubor** [bigfang/jdou#1]
测试了js在本地顺利很运行，异地会有短信验证步骤。请问短信验证问题有办法跳过或者处理吗？未找到好的解决思路。谢谢！

**Comment by bigfang** [comment]
短信验证没法跳过，我也没遇到过，你可以尝试异地登录一次，可能登录一次之后就再也不要求短信验证了。casperjs和node还不太一样，我不知道有啥办法在运行时进行交互
